version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-backend
    container_name: node-backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
    volumes:
      - ./bin:/usr/src/app/bin
      - ./src:/usr/src/app/src
    ports:
      - '3000:3000'
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
