version: '1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-backend
    container_name: node-backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
    networks:
      - api-network
    volumes:
      - ./bin:/usr/src/app/bin
      - ./src:/usr/src/app/src
      - ${LOGS_DIR}:/usr/src/app/logs
      - ${STORAGE_UPLOAD_PATH}:/usr/src/app/public
    ports:
      - '3000:3000'
networks:
  api-network:
    driver: bridge
